public class Fichier7 {
    public void construireChaines() {
        String chaine1 = "Chaîne " + 1 + " construite";
        String chaine2 = "Chaîne " + 2 + " construite";
        String chaine3 = "Chaîne " + 3 + " construite";
        String chaine4 = "Chaîne " + 4 + " construite";
        String chaine5 = "Chaîne " + 5 + " construite";
        String chaine6 = "Chaîne " + 6 + " construite";
        String chaine7 = "Chaîne " + 7 + " construite";
        String chaine8 = "Chaîne " + 8 + " construite";
        String chaine9 = "Chaîne " + 9 + " construite";
        String chaine10 = "Chaîne " + 10 + " construite";
        String chaine11 = "Chaîne " + 11 + " construite";
        String chaine12 = "Chaîne " + 12 + " construite";
        String chaine13 = "Chaîne " + 13 + " construite";
        String chaine14 = "Chaîne " + 14 + " construite";
        String chaine15 = "Chaîne " + 15 + " construite";
        String chaine16 = "Chaîne " + 16 + " construite";
        String chaine17 = "Chaîne " + 17 + " construite";
        String chaine18 = "Chaîne " + 18 + " construite";
        String chaine19 = "Chaîne " + 19 + " construite";
        String chaine20 = "Chaîne " + 20 + " construite";
        String chaine21 = "Chaîne " + 21 + " construite";
        String chaine22 = "Chaîne " + 22 + " construite";
        String chaine23 = "Chaîne " + 23 + " construite";
        String chaine24 = "Chaîne " + 24 + " construite";
        String chaine25 = "Chaîne " + 25 + " construite";
        String chaine26 = "Chaîne " + 26 + " construite";
        String chaine27 = "Chaîne " + 27 + " construite";
        String chaine28 = "Chaîne " + 28 + " construite";
        String chaine29 = "Chaîne " + 29 + " construite";
        String chaine30 = "Chaîne " + 30 + " construite";
        String chaine31 = "Chaîne " + 31 + " construite";
        String chaine32 = "Chaîne " + 32 + " construite";
        String chaine33 = "Chaîne " + 33 + " construite";
        String chaine34 = "Chaîne " + 34 + " construite";
        String chaine35 = "Chaîne " + 35 + " construite";
        String chaine36 = "Chaîne " + 36 + " construite";
        String chaine37 = "Chaîne " + 37 + " construite";
        String chaine38 = "Chaîne " + 38 + " construite";
        String chaine39 = "Chaîne " + 39 + " construite";
        String chaine40 = "Chaîne " + 40 + " construite";
        String chaine41 = "Chaîne " + 41 + " construite";
        String chaine42 = "Chaîne " + 42 + " construite";
        String chaine43 = "Chaîne " + 43 + " construite";
        String chaine44 = "Chaîne " + 44 + " construite";
        String chaine45 = "Chaîne " + 45 + " construite";
        String chaine46 = "Chaîne " + 46 + " construite";
        String chaine47 = "Chaîne " + 47 + " construite";
        String chaine48 = "Chaîne " + 48 + " construite";
        String chaine49 = "Chaîne " + 49 + " construite";
        String chaine50 = "Chaîne " + 50 + " construite";
        System.out.println(chaine1);
        System.out.println(chaine2);
        System.out.println(chaine3);
        System.out.println(chaine4);
        System.out.println(chaine5);
        System.out.println(chaine6);
        System.out.println(chaine7);
        System.out.println(chaine8);
        System.out.println(chaine9);
        System.out.println(chaine10);
        System.out.println(chaine11);
        System.out.println(chaine12);
        System.out.println(chaine13);
        System.out.println(chaine14);
        System.out.println(chaine15);
        System.out.println(chaine16);
        System.out.println(chaine17);
        System.out.println(chaine18);
        System.out.println(chaine19);
        System.out.println(chaine20);
        System.out.println(chaine21);
        System.out.println(chaine22);
        System.out.println(chaine23);
        System.out.println(chaine24);
        System.out.println(chaine25);
        System.out.println(chaine26);
        System.out.println(chaine27);
        System.out.println(chaine28);
        System.out.println(chaine29);
        System.out.println(chaine30);
        System.out.println(chaine31);
        System.out.println(chaine32);
        System.out.println(chaine33);
        System.out.println(chaine34);
        System.out.println(chaine35);
        System.out.println(chaine36);
        System.out.println(chaine37);
        System.out.println(chaine38);
        System.out.println(chaine39);
        System.out.println(chaine40);
        System.out.println(chaine41);
        System.out.println(chaine42);
        System.out.println(chaine43);
        System.out.println(chaine44);
        System.out.println(chaine45);
        System.out.println(chaine46);
        System.out.println(chaine47);
        System.out.println(chaine48);
        System.out.println(chaine49);
        System.out.println(chaine50);
    }
}