public class Fichier5 {
    public void variablesEtAffichage() {
        double valeur1 = 1.0;
        double valeur2 = 2.0;
        double valeur3 = 3.0;
        double valeur4 = 4.0;
        double valeur5 = 5.0;
        double valeur6 = 6.0;
        double valeur7 = 7.0;
        double valeur8 = 8.0;
        double valeur9 = 9.0;
        double valeur10 = 10.0;
        double valeur11 = 11.0;
        double valeur12 = 12.0;
        double valeur13 = 13.0;
        double valeur14 = 14.0;
        double valeur15 = 15.0;
        double valeur16 = 16.0;
        double valeur17 = 17.0;
        double valeur18 = 18.0;
        double valeur19 = 19.0;
        double valeur20 = 20.0;
        double valeur21 = 21.0;
        double valeur22 = 22.0;
        double valeur23 = 23.0;
        double valeur24 = 24.0;
        double valeur25 = 25.0;
        double valeur26 = 26.0;
        double valeur27 = 27.0;
        double valeur28 = 28.0;
        double valeur29 = 29.0;
        double valeur30 = 30.0;
        double valeur31 = 31.0;
        double valeur32 = 32.0;
        double valeur33 = 33.0;
        double valeur34 = 34.0;
        double valeur35 = 35.0;
        double valeur36 = 36.0;
        double valeur37 = 37.0;
        double valeur38 = 38.0;
        double valeur39 = 39.0;
        double valeur40 = 40.0;
        double valeur41 = 41.0;
        double valeur42 = 42.0;
        double valeur43 = 43.0;
        double valeur44 = 44.0;
        double valeur45 = 45.0;
        double valeur46 = 46.0;
        double valeur47 = 47.0;
        double valeur48 = 48.0;
        double valeur49 = 49.0;
        double valeur50 = 50.0;
        System.out.println("Double valeur: " + valeur1);
        System.out.println("Double valeur: " + valeur2);
        System.out.println("Double valeur: " + valeur3);
        System.out.println("Double valeur: " + valeur4);
        System.out.println("Double valeur: " + valeur5);
        System.out.println("Double valeur: " + valeur6);
        System.out.println("Double valeur: " + valeur7);
        System.out.println("Double valeur: " + valeur8);
        System.out.println("Double valeur: " + valeur9);
        System.out.println("Double valeur: " + valeur10);
        System.out.println("Double valeur: " + valeur11);
        System.out.println("Double valeur: " + valeur12);
        System.out.println("Double valeur: " + valeur13);
        System.out.println("Double valeur: " + valeur14);
        System.out.println("Double valeur: " + valeur15);
        System.out.println("Double valeur: " + valeur16);
        System.out.println("Double valeur: " + valeur17);
        System.out.println("Double valeur: " + valeur18);
        System.out.println("Double valeur: " + valeur19);
        System.out.println("Double valeur: " + valeur20);
        System.out.println("Double valeur: " + valeur21);
        System.out.println("Double valeur: " + valeur22);
        System.out.println("Double valeur: " + valeur23);
        System.out.println("Double valeur: " + valeur24);
        System.out.println("Double valeur: " + valeur25);
        System.out.println("Double valeur: " + valeur26);
        System.out.println("Double valeur: " + valeur27);
        System.out.println("Double valeur: " + valeur28);
        System.out.println("Double valeur: " + valeur29);
        System.out.println("Double valeur: " + valeur30);
        System.out.println("Double valeur: " + valeur31);
        System.out.println("Double valeur: " + valeur32);
        System.out.println("Double valeur: " + valeur33);
        System.out.println("Double valeur: " + valeur34);
        System.out.println("Double valeur: " + valeur35);
        System.out.println("Double valeur: " + valeur36);
        System.out.println("Double valeur: " + valeur37);
        System.out.println("Double valeur: " + valeur38);
        System.out.println("Double valeur: " + valeur39);
        System.out.println("Double valeur: " + valeur40);
        System.out.println("Double valeur: " + valeur41);
        System.out.println("Double valeur: " + valeur42);
        System.out.println("Double valeur: " + valeur43);
        System.out.println("Double valeur: " + valeur44);
        System.out.println("Double valeur: " + valeur45);
        System.out.println("Double valeur: " + valeur46);
        System.out.println("Double valeur: " + valeur47);
        System.out.println("Double valeur: " + valeur48);
        System.out.println("Double valeur: " + valeur49);
        System.out.println("Double valeur: " + valeur50);
    }
}