public class Vide {
    public void vide() {
        String message1 = "Ceci est un message numéro 1";
        String message2 = "Ceci est un message numéro 2";
        String message3 = "Ceci est un message numéro 3";
        String message4 = "Ceci est un message numéro 4";
        String message5 = "Ceci est un message numéro 5";
        String message6 = "Ceci est un message numéro 6";
        String message7 = "Ceci est un message numéro 7";
        String message8 = "Ceci est un message numéro 8";
        String message9 = "Ceci est un message numéro 9";
        String message10 = "Ceci est un message numéro 10";
        String message11 = "Ceci est un message numéro 11";
        String message12 = "Ceci est un message numéro 12";
        String message13 = "Ceci est un message numéro 13";
        String message14 = "Ceci est un message numéro 14";
        String message15 = "Ceci est un message numéro 15";
        String message16 = "Ceci est un message numéro 16";
        String message17 = "Ceci est un message numéro 17";
        String message18 = "Ceci est un message numéro 18";
        String message19 = "Ceci est un message numéro 19";
        String message20 = "Ceci est un message numéro 20";
        String message21 = "Ceci est un message numéro 21";
        String message22 = "Ceci est un message numéro 22";
        String message23 = "Ceci est un message numéro 23";
        String message24 = "Ceci est un message numéro 24";
        String message25 = "Ceci est un message numéro 25";
        String message26 = "Ceci est un message numéro 26";
        String message27 = "Ceci est un message numéro 27";
        String message28 = "Ceci est un message numéro 28";
        String message29 = "Ceci est un message numéro 29";
        String message30 = "Ceci est un message numéro 30";
        String message31 = "Ceci est un message numéro 31";
        String message32 = "Ceci est un message numéro 32";
        String message33 = "Ceci est un message numéro 33";
        String message34 = "Ceci est un message numéro 34";
        String message35 = "Ceci est un message numéro 35";
        String message36 = "Ceci est un message numéro 36";
        String message37 = "Ceci est un message numéro 37";
        String message38 = "Ceci est un message numéro 38";
        String message39 = "Ceci est un message numéro 39";
        String message40 = "Ceci est un message numéro 40";
        String message41 = "Ceci est un message numéro 41";
        String message42 = "Ceci est un message numéro 42";
        String message43 = "Ceci est un message numéro 43";
        String message44 = "Ceci est un message numéro 44";
        String message45 = "Ceci est un message numéro 45";
        String message46 = "Ceci est un message numéro 46";
        String message47 = "Ceci est un message numéro 47";
        String message48 = "Ceci est un message numéro 48";
        String message49 = "Ceci est un message numéro 49";
        String message50 = "Ceci est un message numéro 50";

        System.out.println(message1);
        System.out.println(message2);
        System.out.println(message3);
        System.out.println(message4);
        System.out.println(message5);
        System.out.println(message6);
        System.out.println(message7);
        System.out.println(message8);
        System.out.println(message9);
        System.out.println(message10);
        System.out.println(message11);
        System.out.println(message12);
        System.out.println(message13);
        System.out.println(message14);
        System.out.println(message15);
        System.out.println(message16);
        System.out.println(message17);
        System.out.println(message18);
        System.out.println(message19);
        System.out.println(message20);
        System.out.println(message21);
        System.out.println(message22);
        System.out.println(message23);
        System.out.println(message24);
        System.out.println(message25);
        System.out.println(message26);
        System.out.println(message27);
        System.out.println(message28);
        System.out.println(message29);
        System.out.println(message30);
        System.out.println(message31);
        System.out.println(message32);
        System.out.println(message33);
        System.out.println(message34);
        System.out.println(message35);
        System.out.println(message36);
        System.out.println(message37);
        System.out.println(message38);
        System.out.println(message39);
        System.out.println(message40);
        System.out.println(message41);
        System.out.println(message42);
        System.out.println(message43);
        System.out.println(message44);
        System.out.println(message45);
        System.out.println(message46);
        System.out.println(message47);
        System.out.println(message48);
        System.out.println(message49);
        System.out.println(message50);
    }
}
